### PR TITLE
fix(IdP-config): fix users upload functionality for json format

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**
## Description

Fixed blank page and json upload functionality to backend

## Why

UI Improvements

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/441

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
Unfortunately I still get the following error every time I download the current user list in json format and upload the same json file again:
` ERROR User Migration list format wrong. Missing or incorrect header line. Recheck the download file to retrieve the expected format,`

**Review by oyo — APPROVED** [review]

**Comment by nidhigarg-bmw** [comment]
> Unfortunately I still get the following error every time I download the current user list in json format and upload the same json file again: ` ERROR User Migration list format wrong. Missing or incorrect header line. Recheck the download file to retrieve the expected format,`

@evegufy There was error in json headers list. Please check now.

**Review by evegufy — CHANGES_REQUESTED** [review]
It works better now, I'm able to download and to upload the json file now, but the json results like this after upload:
```
    "identityProviders": [
      {
        "identityProviderId": "[object Object]\"",
        "userId": "",
        "userName": ""
      }
```
I don't think that there backend will be able to coupe with `[object Object]\"` identityProviderId.

**Review by evegufy — APPROVED** [review]
tested successfully

**Pull request merged**
