### PR TITLE
feat(static pages): use new subanavigation component

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

use new sub navigation menu to support multi device.
this has been used in Static Pages - Company Roles, Use Case, Data Space

## Why

one being multi device able and the other one not.

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by manojava-gk** [comment]
FYI - Zero linter issues in this PR :)

**Comment by manojava-gk** [comment]
This PR is dependent on this new component https://github.com/eclipse-tractusx/portal-shared-components/pull/78

**Comment by manojava-gk** [comment]
This is dependent on https://github.com/eclipse-tractusx/portal-frontend/pull/374

**Comment by jjeroch** [comment]
@manojava-gk the pr and the changeLog is refering to a new "sub navigation ui"
I would have expected that its rather an update of the "sub navigation menu" component. Isnt it?
Also could you please mention the respective section where the component was updated (mention it for the ChangeLogs and in the PR description please)

**Review by jjeroch — CHANGES_REQUESTED** [review]
Comment added

**Review by oyo — APPROVED** [review]

**Pull request merged**
