### PR TITLE
fix: update type issues caused by the removal of 'any' type in shared components

### PR DESCRIPTION
**Pull request by shahmargi12**
## Description

Fix type errors caused by type changes in shared components.

**Reference:**
- Removal of `any` type: [PR #312](https://github.com/eclipse-tractusx/portal-shared-components/pull/312)

## Why

- The shared components now use stricter types for improved type safety.
- Updating the code ensures consistency and prevents type-related issues with the shared components.
- Avoids runtime errors and ensures the app functions correctly after the shared component updates.

## Issue

[1110](https://github.com/eclipse-tractusx/portal-frontend/issues/1110)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by manojava-gk — APPROVED** [review]
lftm

**Comment by manojava-gk** [comment]
@shahmargi12 Steps to follow when portal is dependent on shared-component
1. upgrade shared-component dependency to 3.6.1 in package.json
2. run `yarn` to upgrade `yarn.lock` (eventually delete node_modules folder)
3. push again

**Comment by shahmargi12** [comment]
> @shahmargi12 Steps to follow when portal is dependent on shared-component
> 
> 1. upgrade shared-component dependency to 3.6.1 in package.json
> 2. run `yarn` to upgrade `yarn.lock` (eventually delete node_modules folder)
> 3. push again

@manojava-gk I've updated shared-component to 3.6.1 and pushed the changes.

**Comment by oyo** [comment]
> @manojava-gk I've updated shared-component to 3.6.1 and pushed the changes.

@shahmargi12 Thanks. The license request for shared components 3.6.x is still in progress - we need to wait for an approval there. Status: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16144

**Comment by shahmargi12** [comment]
> > @manojava-gk I've updated shared-component to 3.6.1 and pushed the changes.
> 
> @shahmargi12 Thanks. The license request for shared components 3.6.x is still in progress - we need to wait for an approval there. Status: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16144

@oyo Thanks for the update

**Review by oyo — APPROVED** [review]

**Pull request merged**
