### PR TITLE
fix: change required role for app user role overlay

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

Change of roles corresponding to add/edit app user role overlays.

## Why

This is for consistency with backend endpoint. [owncompany/users/{companyUserId}/apps/{appId}/roles](https://github.com/eclipse-tractusx/portal-backend/blob/a0b4b0d5729252bdf5b012d4cd592789092b68aa/src/administration/Administration.Service/Controllers/UserController.cs#L239)

## Issue

Refs: #822

## Checklist

- [x] I have performed a self-review of my own code

## Note
Edits by maintainers allowed:
image

### CODE REVIEW

**Review by saadanzari — APPROVED** [review]
lgtm

**Review by jjeroch — CHANGES_REQUESTED** [review]
Nice - however I suggest to add the permission validation on button level as well. Button should be deactivated or hidden if the permission is not available

**Comment by typecastcloud** [comment]
> Nice - however I suggest to add the permission validation on button level as well. Button should be deactivated or hidden if the permission is not available

I think the logic for that already exists. Please confirm @oyo.

image
image

**Review by oyo — APPROVED** [review]

**Comment by oyo** [comment]
> > Nice - however I suggest to add the permission validation on button level as well. Button should be deactivated or hidden if the permission is not available
> 
> I think the logic for that already exists. Please confirm @oyo. Since I only changed the linked role to overlay. I did not test this in my local environment because I have some issues with app setup steps.

It's not implemented:
https://github.com/eclipse-tractusx/portal-frontend/blob/release/v2.0.0-RC9/src/components/pages/AppUserManagement/components/AppUserDetailsTable/index.tsx#L51

Currently the button is only disabled if there are no roles available. 
`addButtonDisabled={roles && roles?.length <= 0}`

To also disable if the active user doesn't have the role change to
`addButtonDisabled={(roles && roles?.length <= 0) ?? !UserService.hasRole(ROLES.MODIFY_USER_ACCOUNT)}`

**Review by oyo — APPROVED** [review]

**Review by jjeroch — CHANGES_REQUESTED** [review]
We are getting there ;) now the "Add Roles" button has the new function. But on the FE side there is the "Edit" button as well. The same function is needed for this button (and only for this specific page) as well. Please ensure that this has no impacts on any other "Edit" buttons!! :)

image

**Review by oyo — APPROVED** [review]

**Comment by oyo** [comment]
> But on the FE side there is the "Edit" button as well. The same function is needed for this button (and only for this specific page) as well. Please ensure that this has no impacts on any other "Edit" buttons!! :)

@jjeroch updated the PR now - are we happy now?

**Comment by jjeroch** [comment]
> > But on the FE side there is the "Edit" button as well. The same function is needed for this button (and only for this specific page) as well. Please ensure that this has no impacts on any other "Edit" buttons!! :)
> 
> @jjeroch updated the PR - are we happy now?

we are happy now ;)

**Pull request merged**
