### PR TITLE
feat(linter): add type for imports

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**
## Description

add types for imports

## Why

To remove lint errors

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

### CODE REVIEW

**Comment by jjeroch** [comment]
@manojava-gk  please take over the first review cycle, thanks

**Review by manojava-gk — APPROVED** [review]
lftm

**Comment by oyo** [comment]
please resolve conflicts

**Comment by oyo** [comment]
@evegufy can you check what's the matter with the ECA here?

**Comment by evegufy** [comment]
> Details

@oyo the check looks fine for everything else other than this pending status.
Let's wait until the conflicts are solved, if the issue persists tomorrow we should check if it blocks the merge and if so open a ticket to the EF helpdesk.

**Review by oyo — APPROVED** [review]

**Pull request merged**
