### PR TITLE
bugfix(static pages): increase bottom space

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

increase padding bottom of the last element in the static template page

## Why

Footer / Page Background color issue

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Comment by manojava-gk** [comment]
CHANGELOG note is already present

**Comment by jjeroch** [comment]
@manojava-gk please add an image of the solution - i dont want to merge this as long as we dont know if the issue is really fixed. Please add an image here

**Comment by manojava-gk** [comment]
> @manojava-gk please add an image of the solution - i dont want to merge this as long as we dont know if the issue is really fixed. Please add an image
Screenshot 2023-09-13 at 12 37 12 PM
 here

**Comment by jjeroch** [comment]
> > @manojava-gk please add an image of the solution - i dont want to merge this as long as we dont know if the issue is really fixed. Please add an image
> 
> Screenshot 2023-09-13 at 12 37 12 PM here

@manojava-gk still the same issue - the white section between the last content element and the actual orange footer should not be existing

**Review by jjeroch — CHANGES_REQUESTED** [review]
White section to be removed

**Review by oyo — APPROVED** [review]

**Pull request merged**
