### PR TITLE
fix(app subscription): allow empty url in register url overlay

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**
## Description

Inability to Delete URL in "Register URL for Autosetup" Function on App Subscription Page

## Why

Function does not support deleting the registered URL, which is causing inconvenience and limiting the functionality of the application.

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/793

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

### CODE REVIEW

**Review by oyo — APPROVED** [review]

**Comment by nidhigarg-bmw** [comment]
@oyo Please merge this PR

**Review by oyo — APPROVED** [review]

**Comment by oyo** [comment]
> @oyo Please merge this PR

@nidhigarg-bmw I'm unable to merge this one as long as @evegufy has change requests open

**Review by evegufy — DISMISSED** [review]

**Comment by evegufy** [comment]
@nidhigarg-bmw please solve the conflict in changelog again?

**Comment by nidhigarg-bmw** [comment]
@

> @nidhigarg-bmw please solve the conflict in changelog again?

@evegufy Resolved the conflicts.

**Review by evegufy — APPROVED** [review]

**Pull request merged**
