### PR TITLE
fix: service details de description limitation

### PR DESCRIPTION
**Pull request by JordanGerada3**
## Description

- Updated REGEX to allow all special characters in DE & EN for service onboarding short and long descriptions

## Why

- Input validation REGEX was blocking entering text in DE description boxes of Service Release Process when using some special characters. It also make sense to do the same for EN incase their are scenarios where the user would like to mention their company name which might also include umlauts and special characters. 

## Issue

#965 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by JordanGerada3** [comment]
@MaximilianHauer I have reverted and applied the 10 character minimum to "longDesctription". Please let me know if this is the correct way of managing this.

**Review by MaximilianHauer — APPROVED** [review]

**Comment by MaximilianHauer** [comment]
@oyo  can be merged from my perspective

**Review by Phil91 — COMMENTED** [review]
how does this solve the error? it only sets the validation of the min characters from 9 to 10? can the error be reproduced? The adjusted regex does allow everything in my opinion as long as it is 10 characters long (previously 9)

**Comment by MaximilianHauer** [comment]
@Phil91  initial PR was https://github.com/eclipse-tractusx/portal-frontend/pull/993 but my comment was not included thats why we created another PR

**Review by Phil91 — APPROVED** [review]

**Comment by Phil91** [comment]
> @Phil91 initial PR was #993 but my comment was not included thats why we created another PR

@MaximilianHauer thanks for the explanation. PR approved and merged

**Comment by ybidois** [comment]
@Phil91 @oyo did we forget to merge this?

**Review by oyo — APPROVED** [review]

**Comment by oyo** [comment]
> @Phil91 @oyo did we forget to merge this?

done :)

**Pull request merged**
