### PR TITLE
feat: subscription detail page for customer

### PR DESCRIPTION
**Pull request by charmi-v**
## Description

Enhanced the Subscribed Detail Page for customer :
- Improved the App Information section with subscribed app details (including images, language, documents, and privacy).
- Added Technical User Details with a link to user details, visible to users with the view_tech_user_management role.
- Optimized responsiveness for mobile, tablet, and full display screens.

Preview 
LargeScreen

## Why

Extended the subscription detail page to include more comprehensive app-related information.

## Issue

#939 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by manojava-gk** [comment]
optimise and create common file to reduce duplication issue

**Comment by charmi-v** [comment]
@manojava-gk I have optimized the code block that appeared duplicated in failing action check 
- However, the SonarCloud analysis has not been triggered for this new commit, and the analysis still reflects the code from the previous commit. 
- Could you please advise on how to trigger the SonarCloud code analysis action for the latest commit within the same pull request?

**Comment by manojava-gk** [comment]
> @manojava-gk I have optimized the code block that appeared duplicated in failing action check
> 
> * However, the SonarCloud analysis has not been triggered for this new commit, and the analysis still reflects the code from the previous commit.
> * Could you please advise on how to trigger the SonarCloud code analysis action for the latest commit within the same pull request?

As per the PR and sonar cloud dashboard, it has run on your recent commit(c9beed8abba3b14e7325726809029ee279c346ab)not the old.

**Comment by charmi-v** [comment]
The duplicated code block highlighted in the SonarCloud Code Analysis does not reflects the changes made in the most recent [commit](https://github.com/eclipse-tractusx/portal-frontend/commit/c9beed8abba3b14e7325726809029ee279c346ab#diff-16f0e04fd836be3c6e6897dbf1fd161b6d79955524ac961c23bfdabb5226f729).

@manojava-gk Could you please validate that ? I believe that if we manually trigger the SonarCloud code analysis action, the analysis will update accordingly.

**Comment by charmi-v** [comment]
> > @manojava-gk I have optimized the code block that appeared duplicated in failing action check
> > 
> > * However, the SonarCloud analysis has not been triggered for this new commit, and the analysis still reflects the code from the previous commit.
> > * Could you please advise on how to trigger the SonarCloud code analysis action for the latest commit within the same pull request?
> 
> As per the PR and sonar cloud dashboard, it has run on your recent commit([c9beed8](https://github.com/eclipse-tractusx/portal-frontend/commit/c9beed8abba3b14e7325726809029ee279c346ab))not the old.

@manojava-gk Issue resolved now

**Comment by manojava-gk** [comment]
@charmi-v  Kindly fix the issues from sonar cloud. Pretty straight forward.

**Comment by charmi-v** [comment]
> @charmi-v Kindly fix the issues from sonar cloud. Pretty straight forward.

@manojava-gk  Resolved

**Review by manojava-gk — APPROVED** [review]
lftm. But add notes in CHANGELOG.md file

**Comment by charmi-v** [comment]
> lftm. But add notes in CHANGELOG.md file

Updated the description in CHANGELOG.md file

**Review by oyo — DISMISSED** [review]

**Review by oyo — APPROVED** [review]

**Pull request merged**
