### PR TITLE
chore: upgrade app dependencies

### PR DESCRIPTION
**Pull request by oyo**
## Description

Upgrade dependent libraries

## Why

Regular procedure to get latest bugfixes.

## Issue

#1120 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by oyo** [comment]
License review requests have already been issued with another PR:
https://github.com/eclipse-tractusx/portal-shared-components/pull/337#issuecomment-2382649287

**Review by evegufy — CHANGES_REQUESTED** [review]
could you please look into https://github.com/eclipse-tractusx/portal-frontend/pull/1181#issuecomment-2383035922

**Comment by oyo** [comment]
> could you please look into [#1181 (comment)](https://github.com/eclipse-tractusx/portal-frontend/pull/1181#issuecomment-2383035922)

issue resolved

**Comment by evegufy** [comment]
not possible to review yet because one IP review issues isn't approved yet

**Pull request merged**
