### PR TITLE
fix: add missing short name to form

### PR DESCRIPTION
**Pull request by JordanGerada3**
## Description

- Added shortName (legal name) to form
- Added translations EN, DE

## Why

Necessary information such as short name that  should be user verified before registering was not available in the form. 

## Issue

#1338 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by Usmanfee — APPROVED** [review]
lgtm

**Review by shubhamv-ss — APPROVED** [review]
LGTM

**Review by saadanzari — APPROVED** [review]

**Comment by manojava-gk** [comment]
Kindly add changelog entry

**Comment by JordanGerada3** [comment]
> Kindly add changelog entry

@manojava-gk changelog now updated, thank you!

> Kindly add changelog entry

@manojava-gk changelog now added, thank you!

**Review by manojava-gk — APPROVED** [review]

**Review by oyo — APPROVED** [review]

**Pull request merged**
