### PR TITLE
fix: Overview My App button not working on App Release Process page

### PR DESCRIPTION
**Pull request by ss-nikunj**
## Description

- The "Overview My Apps" button is not working whenever the user clicks the button. It should be working like the Service Release Process and redirect to the respective page (App Overview Page)

## Why
- 'Overview my apps' button is not working on the App Release Process page.

## Issue

[Link to Github issue.
](https://github.com/eclipse-tractusx/portal-frontend/issues/1022)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by ss-nikunj** [comment]
JUST FOR YOUR REFERENCE:
- The onOverviewButton function calls when we click on the Overview My App button, Here you can find "do nothing".

image

**Review by manojava-gk — APPROVED** [review]
lgtm

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Please update changelog.md file

**Comment by ss-nikunj** [comment]
@lavanya-bmw changelog.md file updated

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Review by oyo — APPROVED** [review]

**Pull request merged**
