### PR TITLE
fix: add hint for display name at idp creation

### PR DESCRIPTION
**Pull request by Usmanfee**
## Description
Updated regex for the allowed characters for displayName in idp creation. Previously we were not showing any error message against violation of regex. Updated regex and error translations bases on certain violation.

Changelog entry:
```
- **IdP Creation**
  - added hint for invalid input of display name [#1264](https://github.com/eclipse-tractusx/portal-frontend/issues/1264)
```

## Why
To have better UX to let the user know what he is doing wrong and what is expected for displayName and what type of string value BE expects for displayName.

## Issue
https://github.com/eclipse-tractusx/portal-frontend/issues/1264

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have updated the changelog of my change

### CODE REVIEW

**Review by shubhamv-ss — APPROVED** [review]
Looks good to me!

**Comment by evegufy** [comment]
> Please update changelog

@lavanya-bmw We don't recommend to update the changelog anymore, as it just lead to one conflict after the other and in general issues, we recommend to add it to the PR description now.

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Comment by Usmanfee** [comment]
> Please resolve conflicts

conflicts are resolved.

**Review by manojava-gk — APPROVED** [review]

**Comment by drhansbeck** [comment]
Hi @isaadansari @kunalgaurav-bmw  @ss-nikunj , 

Please review. This is impacting the productive environment.

**Review by evegufy — APPROVED** [review]

**Pull request merged**
