### PR TITLE
feat(marketplace): Added tech user setup section

### PR DESCRIPTION
**Pull request by lavanya-bmw**
## Description

Added tech user setup section to app marketplace and service marketplace

## Why

To update app and service marketplace with tech user setup

## Issue

Ref: 2619, 2623

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by manojava-gk — APPROVED** [review]
lftm

**Review by manojava-gk — APPROVED** [review]
lftm

**Review by oyo — APPROVED** [review]

**Review by oyo — CHANGES_REQUESTED** [review]
looks good - but please resolve changelog conflicts

**Comment by jjeroch** [comment]
@lavanya-bmw attention this has still an conflict with the changeLog

**Review by oyo — APPROVED** [review]

**Pull request merged**
