### PR TITLE
fix(idp config): fix user csv file upload results

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**
## Description

Fix upload of user list results in empty preview and when confirming the upload an empty file is sent to the backend.

## Why

Feature broken fix

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/440

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
I tested the branch locally and unfortunately I still observe the same behaviour.
Please also improve the PR title, use an imperative from.
And please link the issue in the PR description https://github.com/eclipse-tractusx/portal-frontend/issues/440.

**Comment by nidhigarg-bmw** [comment]
> I tested the branch locally and unfortunately I still observe the same behaviour. Please also improve the PR title, use an imperative from. And please link the issue in the PR description #440.

I made a change @evegufy Can you please test it again. Hope it will work now

**Review by evegufy — CHANGES_REQUESTED** [review]
@nidhigarg-bmw the file is now shown in the preview before upload, but with a double quote in the end, which leads to the following error at upload:

image

**Comment by nidhigarg-bmw** [comment]
> @nidhigarg-bmw the file is now shown in the preview before upload, but with a double quote in the end, which leads to the following error at upload:
> 
> image

@evegufy  Made the fix. Please test again

**Comment by evegufy** [comment]
@nidhigarg-bmw as discussed, there functionality did work at my retest but did run into a runtime error and the console was showing me an 'maximum update depth exceeded. ' error.

**Comment by nidhigarg-bmw** [comment]
> @nidhigarg-bmw as discussed, there functionality did work at my retest but did run into a runtime error and the console was showing me an 'maximum update depth exceeded. ' error.

@evegufy I made console error fixes. Hope it will work as expected now.

**Review by evegufy — APPROVED** [review]
Retest successful for csv format with my available testdata. 
Still, the entire upload functionality seems a bit fragile to me.
For the topic that json format isn't working at all, I created a separate issue https://github.com/eclipse-tractusx/portal-frontend/issues/441.

**Pull request merged**
