### PR TITLE
fix(quick links): update quick links props

### PR DESCRIPTION
**Pull request by lavanya-bmw**
## Description

Updated props for quick links and shared components package 

## Why

To reflect shared components changes

## Issue

Ref: CPLP-3436

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
please resolve conflict and the failing pr checks, may be connected

**Comment by evegufy** [comment]
> please resolve conflict and the failing pr checks, may be connected

I just noticed that the PR is still in draft, sorry and ignore comment

**Comment by lavanya-bmw** [comment]
> > please resolve conflict and the failing pr checks, may be connected
> 
> I just noticed that the PR is still in draft, sorry and ignore comment

**Comment by lavanya-bmw** [comment]
> > please resolve conflict and the failing pr checks, may be connected
> 
> I just noticed that the PR is still in draft, sorry and ignore comment

@evegufy This PR will be ready for review once https://github.com/eclipse-tractusx/portal-shared-components/pull/103 is merged

**Review by nidhigarg-bmw — APPROVED** [review]
lgtm

**Review by evegufy — APPROVED** [review]

**Pull request merged**
