### PR TITLE
feat(company data): implement pagination

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

implement pagination with load more button in company data page

## Why

pagination is not supported

## Issue

#1026 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by manojava-gk** [comment]
PR check issue is already fixed here - https://github.com/eclipse-tractusx/portal-shared-components/pull/279

**Comment by manojava-gk** [comment]
PR is dependent on - https://github.com/eclipse-tractusx/portal-shared-components/pull/283

**Comment by oyo** [comment]
@manojava-gk this PR has milestone Release 2.2.0 but target branch is set to main - if I change the target to release/v2.2.0-RC2 there are a lot more changes. Please make sure you were branching off the release branch with your commits.

**Review by oyo — CHANGES_REQUESTED** [review]
@manojava-gk this PR has milestone Release 2.2.0 but target branch is set to main - if I change the target to release/v2.2.0-RC2 there are a lot more changes. Please make sure you were branching off the release branch with your commits.

**Comment by manojava-gk** [comment]
@MaximilianHauer this PR is meant for CSV upload. Could you pls remove 2.2.0 tag and priority from here?

**Comment by MaximilianHauer** [comment]
we will include everything csv related into 2.2.0 and if we decide that we wont deploy it we can remove the csv button until the official golive

**Pull request closed without merging**
