### PR TITLE
bugfix(unsubscribe): fix overlay table values

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

overlay table showing wrong information. switch the values between tech user info and connector info

## Why

App Unsubscribe Overlay - wrong information mapping

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Comment by manojava-gk** [comment]
Important: no update of the ChangeLog needed

**Review by nidhigarg-bmw — APPROVED** [review]
lftm

**Comment by jjeroch** [comment]
@manojava-gk  is that really the ideal solution. Asking, since I am surprised that the solution is an update of the order of the attributes. No matter which order is used to display the attributes; always the correct value from the backend api call should get fetched.

**Comment by manojava-gk** [comment]
> @manojava-gk is that really the ideal solution. Asking, since I am surprised that the solution is an update of the order of the attributes. No matter which order is used to display the attributes; always the correct value from the backend api call should get fetched.

Yes this is how we are rendering values from server. This table left hand side has hard code values, so we can not relay completely on server values. We have to map it manually with the appropriate label and value

**Review by oyo — APPROVED** [review]

**Pull request merged**
