### PR TITLE
fix: Add missing RETRIGGER_CREATE_DIM_WALLET type and EndUrl for registration process

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

Add missing RETRIGGER_CREATE_DIM_WALLET  type and EndUrl for registration process

## Why

404 not found if trying to retrigger dim wallet creation.

## Issue

Refs: #997 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

### CODE REVIEW

**Comment by evegufy** [comment]
@Phil91 Please check this change in the context of https://github.com/eclipse-tractusx/sig-release/issues/802
might not be a fix but an enhancement.

cc: @MaximilianHauer

**Review by Phil91 — APPROVED** [review]

**Comment by Phil91** [comment]
there will be some more retrigger steps in the future, on backend side we already added the missing ones and endpoints for some which were existing. Currently available as a PR: https://github.com/eclipse-tractusx/portal-backend/pull/915

**Comment by typecastcloud** [comment]
> there will be some more retrigger steps in the future, on backend side we already added the missing ones and endpoints for some which were existing. Currently available as a PR: [eclipse-tractusx/portal-backend#915](https://github.com/eclipse-tractusx/portal-backend/pull/915)

I can close this PR if someone from frontend is already taking care of all the missing steps.

**Comment by Phil91** [comment]
> > there will be some more retrigger steps in the future, on backend side we already added the missing ones and endpoints for some which were existing. Currently available as a PR: [eclipse-tractusx/portal-backend#915](https://github.com/eclipse-tractusx/portal-backend/pull/915)
> 
> I can close this PR if someone from frontend is already taking care of all the missing steps.

I think we can merge this PR, it's a quick win and one less endpoint / retrigger step we need to implement :)

@oyo could you have a look at it?

**Review by oyo — APPROVED** [review]

**Pull request merged**
