### PR TITLE
bugfix(tech user): update pattern

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

search not working with valid client id. support '-' char in pattern

## Why

search not working with valid client id
'-' char is not supported

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Please add changelog

**Comment by manojava-gk** [comment]
> Please add changelog

It is already present. I had missed this in the previous PR.

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Comment by manojava-gk** [comment]
@evegufy can you merge this PR as Lavanya already reviewd and approved?

**Pull request merged**
